version: '3'

services:
  backend-api:
    env_file:
      - ./.env
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: memories-api
    environment:
      - PORT=$PORT
      - DB_CONNECTION_STRING=$DB_CONNECTION_STRING
      - FRONTEND_URL=$FRONTEND_URL
      - SMTP_USER=$SMTP_USER
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - JWT_SECRET=$JWT_SECRET
      - FORGOT_PASSWORD_EXP_TIME=$FORGOT_PASSWORD_EXP_TIME
      - AWS_BUCKET_NAME=$AWS_BUCKET_NAME
      - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
      - AWS_SECRET_KEY=$AWS_SECRET_KEY
      - AWS_BUCKET_REGION=$AWS_BUCKET_REGION
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - NODE_ENV="dev"
      - LOG_LEVEL="error"
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=6379
      - REDIS_USERNAME=$REDIS_USERNAME
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - "$PORT:$PORT"
    restart: unless-stopped
    command: npm run prod
    stdin_open: true
    tty: true
    volumes:
      - ".:/app/"
