version: '3.8'

services:
  mongo:
    image: mongo
    container_name: memories-db
    restart: unless-stopped
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_ADMINUSERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD

  api-server:
    depends_on:
      - mongo
    container_name: memories-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      MONGODB_ADMINUSERNAME: $MONGODB_USERNAME
      MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      AWS_BUCKET_NAME: $AWS_BUCKET_NAME
      AWS_ACCESS_KEY: $AWS_ACCESS_KEY
      AWS_SECRET_KEY: $AWS_SECRET_KEY
      AWS_BUCKET_REGION: $AWS_BUCKET_REGION
      FORGOT_PASSWORD_EXP_TIME: $FORGOT_PASSWORD_EXP_TIME
      JWT_SECRET: $JWT_SECRET
      PORT: $PORT
      DB_CONNECTION_STRING: $DB_CONNECTION_STRING
      FRONTEND_URL: $FRONTEND_URL
      SMTP_USER: $SMTP_USER
      SMTP_PASSWORD: $SMTP_PASSWORD
  
    command: npm run start
    env_file: ./.env
    ports:
      - "8080:$PORT"
    stdin_open: true
    tty: true
    restart: unless-stopped
